CREATE OR REPLACE PACKAGE "VDB_GOLDILOCKS" 
    AUTHID CURRENT_USER -- what is meaning?
IS
    PROCEDURE "EXECUTE_DDL"(
        DDL IN VARCHAR2);
    
    PROCEDURE "REGISTER_OBJECT"(
        SCHEMA_NAME IN VARCHAR2, OBJECT_NAME IN VARCHAR2)
    PRAGMA BUILTIN('pkg_vdb_goldilocks__register_object');

    PROCEDURE "UNREGISTER_OBJECT"(
        SCHEMA_NAME IN VARCHAR2, OBJECT_NAME IN VARCHAR2)
    PRAGMA BUILTIN('pkg_vdb_goldilocks__unregister_object');

    PROCEDURE "REGISTER_CONNECTION_INFO"(
        VDB_IP IN VARCHAR2,
        VDB_PORT IN VARCHAR2,
        ID IN VARCHAR2,
        PASSWD IN VARCHAR2
    )
    PRAGMA BUILTIN('pkg_vdb_goldilocks__register_connection_info');

    PROCEDURE "UNREGISTER_CONNECTION_INFO"
    PRAGMA BUILTIN('pkg_vdb_goldilocks__unregister_connection_info');
END;
/

CREATE OR REPLACE PUBLIC SYNONYM "VDB_GOLDILOCKS" FOR SYS."VDB_GOLDILOCKS";
GRANT EXECUTE ON SYS.VDB_GOLDILOCKS TO PUBLIC;
